version: '2.1'

services:
  db:
    image: postgres:latest
    hostname: psql
    ports:
      - "5433:5432"  # Changed the host port to 5433
    environment:
      POSTGRES_USER: introduction
      POSTGRES_PASSWORD: introduction
      POSTGRES_DB: todo
    # Optionally, you can add a volume to persist data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
